# Generated by Django 5.0.6 on 2024-06-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('not-confirmed', 'Not-confirmed')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='id_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('not-confirmed', 'Not-confirmed')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('not-confirmed', 'Not-confirmed')], default='pending', max_length=100),
        ),
    ]
