# Generated by Django 4.2.3 on 2024-06-24 12:59

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_dollaraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollaraccount',
            name='dollar_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='AZA', unique=True),
        ),
        migrations.AlterField(
            model_name='dollaraccount',
            name='dollar_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='515', unique=True),
        ),
    ]
