# Generated by Django 4.2.3 on 2024-06-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_dollaraccount_dollar_rate'),
        ('core', '0003_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reciever_dollar_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_dollar_transactions', to='account.dollaraccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_dollar_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_dollar_transactions', to='account.dollaraccount'),
        ),
    ]
