# Generated by Django 4.2.3 on 2024-06-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_reciever_dollar_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_exchange',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
