# Generated by Django 4.2.3 on 2024-06-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_amount_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
