# Generated by Django 4.2.3 on 2024-06-28 20:52

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='rit',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=25, prefix=''),
        ),
    ]
