# Generated by Django 4.2.3 on 2024-06-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_recipient_rit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
