# Generated by Django 4.2.3 on 2024-06-28 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_dollaraccount_dollar_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_alter_recipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='kyc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.kyc'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
