# Generated by Django 4.2.3 on 2024-06-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recipient_kyc_alter_recipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='account_type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('NGN', 'Naira')], default='NGN', max_length=10),
        ),
    ]
