# Generated by Django 4.2.3 on 2024-07-04 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_dollaraccount_dollar_rate'),
        ('core', '0016_alter_recipient_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.kyc'),
        ),
    ]
